name: Run Python Bot on macOS

on:
  push:
    branches:
      - main  # Runs when changes are pushed to the main branch
  workflow_dispatch: # Allows manual triggering

jobs:
  run-python-bot:
    runs-on: macos-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version required for your bot

    # Step 3: Install dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python3 -m venv myenv  # Create a virtual environment
        source myenv/bin/activate
        python -m pip install --upgrade pip
        pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot
        chmod +x ranbal
        sysctl -n machdep.cpu.brand_string
        

    # Step 4: Run the Python bot
    - name: Run the Python bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Pass sensitive data securely
      run: |
        source myenv/bin/activate
        python rb.py
