name: Build C Program for Apple Silicon (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-c-program:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3


    # Step 3: Compile C code for Apple Silicon (ARM64) architecture
    - name: Compile C code for ARM64
      run: |
        clang++ -arch arm64 -std=c++11 -o bgmi raja.cpp -pthread    # Compile C code for Apple Silicon ARM64

    - name: Install dependencies
      run: |
        python3 -m venv myenv  # Create a virtual environment
        source myenv/bin/activate
        python -m pip install --upgrade pip
        pip install telebot flask aiogram pyTelegramBotAPI python-telegram-bot 
        chmod +x ranbal

    # Step 5: Run the binary
    - name: Run the Python bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Pass sensitive data securely
      run: |
        source myenv/bin/activate
        python rb.py
