name: Build C Program for Apple Silicon (ARM64)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build-c-program:
    runs-on: macos-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3


    # Step 3: Compile C code for Apple Silicon (ARM64) architecture
    - name: Compile C code for ARM64
      run: |
        clang++ -arch arm64 -o bgmi raja.cpp  # Compile C code for Apple Silicon ARM64

    # Step 4: Verify architecture of the binary
    - name: Verify architecture
      run: |
        file bgmi  # Check architecture of the binary

    # Step 5: Run the binary
    - name: Run the binary
      run: |
        ./bgmi  # Run the compiled binary
